protocol SettingsPresentable: AnyObject {
    func viewDidLoad()
    func navigateBack()
    func toggleDarkMode(isEnabled: Bool)
    func toggleNotifications(isEnabled: Bool)
    func changeLanguage(to language: String)
    func changeCurrency(to currencyCode: String)
    func toggleEmailNotifications(isEnabled: Bool)
    func togglePushNotifications(isEnabled: Bool)
    func toggleBiometricLogin(isEnabled: Bool)
    func resetToDefaults()
    func didFetchSettings(_ settings: SettingsModel)
    func didUpdateSetting(key: String, value: Any, success: Bool)
    func didFailOperation(with error: String)
}
